import { describe, expect, test } from 'bun:test';
import { db } from '@scani/db/connection';
import * as schema from '@scani/db/schema';
import { eq, sql } from 'drizzle-orm';
import { withTestDb } from '../../test/helpers/db';
import { makeToken } from '../../test/helpers/factories-extra';

/**
 * SC-230. The local gate is the only thing between a bad merge and
 * production on this repo, and for a while it was non-deterministic —
 * differently non-deterministic per machine, so two people could both run
 * `bun run test`, both say "tests pass", and be measuring different things.
 *
 * The cause was a fixture default, not any test: `makeToken`'s symbol was
 * `TOK` plus four hex characters, a space of 65,536, under a unique
 * constraint, called from 127 sites. It ratcheted — a collision failed a
 * test, a test failing partway through its fixture did not finish cleaning
 * up, the surviving rows narrowed the free space, and the next run was
 * likelier to collide.
 *
 * These two tests are the guard, and they are deterministic where the bug
 * was probabilistic. A probabilistic bug cannot be caught by a
 * probabilistic test that passes 77% of the time.
 */
describe('test fixtures do not contaminate the shared database', () => {
  /**
   * The invariant the whole suite rests on: work done inside `withTestDb`
   * is rolled back. 37 files assume this. Nothing asserted it.
   *
   * Asserted on `tokens` specifically because that is the table that
   * actually leaked, and the assertion is a COUNT taken before and after
   * rather than a lookup of the row — a lookup would pass if the row
   * survived under a different id.
   */
  test('a row created inside withTestDb is gone once the callback returns', async () => {
    const before = await db
      .select({ n: sql<number>`count(*)::int` })
      .from(schema.tokens)
      .then((r) => r[0]?.n ?? 0);

    let createdId: string | undefined;
    await withTestDb(async (tx) => {
      const token = await makeToken(tx, { name: 'SC-230 isolation probe' });
      createdId = token.id;
      // Visible inside the transaction — otherwise this test would pass
      // simply because the insert silently failed.
      const inside = await tx
        .select({ n: sql<number>`count(*)::int` })
        .from(schema.tokens)
        .then((r) => r[0]?.n ?? 0);
      expect(inside).toBe(before + 1);
    });

    const after = await db
      .select({ n: sql<number>`count(*)::int` })
      .from(schema.tokens)
      .then((r) => r[0]?.n ?? 0);

    expect(after).toBe(before);
    expect(createdId).toBeDefined();
    const survivors = await db
      .select({ id: schema.tokens.id })
      .from(schema.tokens)
      .where(eq(schema.tokens.id, createdId as string));
    expect(survivors).toHaveLength(0);
  });

  /**
   * The collision space, asserted directly rather than sampled.
   *
   * A test that generates N symbols and checks they are distinct would have
   * passed against the broken four-character version roughly 89% of the
   * time, which is worse than no test — it would have been cited as
   * evidence the fixture was fine.
   *
   * So this asserts the PROPERTY that made collisions negligible: the
   * generated symbol carries a full uuid's worth of entropy. 32 hex
   * characters is 2^128; four was 2^16.
   */
  test('the generated symbol is wide enough that collisions are not a matter of luck', async () => {
    await withTestDb(async (tx) => {
      const a = await makeToken(tx);
      const b = await makeToken(tx);

      expect(a.symbol).not.toBe(b.symbol);
      for (const symbol of [a.symbol, b.symbol]) {
        expect(symbol.startsWith('TOK')).toBe(true);
        // The entropy, not merely the difference between these two.
        expect(symbol.slice(3)).toMatch(/^[0-9A-F]{32}$/);
      }
    });
  });

  /**
   * An explicit symbol must still win, or every caller that pins one to
   * assert on it breaks.
   */
  test('an explicit symbol is respected', async () => {
    await withTestDb(async (tx) => {
      const token = await makeToken(tx, { symbol: 'SC230FIXED' });
      expect(token.symbol).toBe('SC230FIXED');
    });
  });

  /**
   * The rows that were already stranded, named so they can be recognised.
   *
   * 138 `TOK####` rows had accumulated in the shared local database by the
   * time this was found. They were deleted, and no holding referenced any
   * of them. This test fails if they come back, which is the cheapest
   * possible detector for the ratchet restarting — the old format cannot
   * be generated by the fixture any more, so any row matching it is a leak
   * from a checkout that predates this fix.
   */
  test('no row is left over from the narrow-symbol era', async () => {
    const legacy = await db
      .select({ symbol: schema.tokens.symbol })
      .from(schema.tokens)
      .where(sql`${schema.tokens.symbol} ~ '^TOK[0-9A-F]{4}$'`);

    expect(
      legacy.map((r) => r.symbol),
      'Stranded fixture tokens from before SC-230. Delete them: ' +
        "delete from tokens where symbol ~ '^TOK[0-9A-F]{4}$'"
    ).toEqual([]);
  });
});
