#!/usr/bin/env bash
#
# Generates apps/admin/.env.local from ~/.secrets plus the admin-specific
# auth vars. Run once after cloning, and re-run whenever ~/.secrets changes.
#
# Usage:
#   apps/admin/scripts/sync-env.sh
#
# Never commit .env.local — it's in .gitignore.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADMIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SECRETS="$HOME/.secrets"
OUT="$ADMIN_DIR/.env.local"

if [ ! -f "$SECRETS" ]; then
  echo "~/.secrets not found at $SECRETS" >&2
  exit 1
fi

{
  echo "# Generated by scripts/sync-env.sh — do not edit."
  echo "# Regenerate with: apps/admin/scripts/sync-env.sh"
  echo ""
  echo "# Provider tokens (copied from ~/.secrets)"
  grep -E '^(export\s+)?[A-Z0-9_]+\s*=' "$SECRETS" | sed 's/^export[[:space:]]\+//'
  echo ""
  echo "# Admin auth — local dev defaults"
  echo "ADMIN_DEV_BYPASS=1"
  echo ""
  echo "# To test the real passkey flow locally, comment out ADMIN_DEV_BYPASS"
  echo "# above, run 'bun run register-passkey', and paste the output here."
} > "$OUT"

echo "wrote $OUT ($(grep -c '=' "$OUT") vars)"
