-- SC-325 / SC-323: one row per externally-addressed position.
--
-- `external_id` is the address an importer dedupes on — the contract
-- `HoldingRepository.findByAccountTokenAndExternalId` has stated since it was
-- written, and the one `findForIngest` restores by preferring NOT NULL rows
-- (SC-193). That lookup takes the first result and assumes there is only one;
-- nothing enforced it. Two rows sharing an address means an importer forked its
-- own position, and every later sync and every ingested transaction then lands
-- on a coin flip — which is how the Airwallex history came to be recorded twice
-- against two rows (48 rows / 24 events / 44,340.05 USD of gross volume).
--
-- PARTIAL, and NOT `NULLS NOT DISTINCT`. Both SC-325's proposed
-- `(account_id, token_id)` and SC-323's `(account_id, token_id, external_id)
-- NULLS NOT DISTINCT` forbid a shape production holds and the user actively
-- maintains: four manual RUB rows in one Tinkoff account, created 2026-05-17
-- from one screenshot parse that returned four lines, then each independently
-- re-confirmed against a second upload on 2026-07-05 — 3053.60→6737.60,
-- 54121.34→55120.85, 69428.89→70077.53, 5683.47→5413.77. Four different
-- deltas, one of them negative. Those are four real products on one Tinkoff
-- screen, not one aggregate split into lines, and no automatic repair keeps
-- all four: merge-and-sum collapses positions the user maintains separately,
-- keep-newest deletes ~137,000 RUB.
--
-- A row with no external_id is not addressable by any importer, so uniqueness
-- says nothing about it. Whether an account may hold two hand-entered rows for
-- one token is a product policy, and it is already enforced at the only door
-- they come through — `CreateHoldingsWithDependenciesUseCase` refuses the
-- payload (SC-303). Policy in the app, invariant in the database.
--
-- No backfill: the violating population under this key is empty in production
-- (measured 2026-08-17, 86 holdings, 0 groups). If a fork appears between now
-- and deploy, this fails with the offending key named in the error DETAIL,
-- which is the actionable form of the failure.
CREATE UNIQUE INDEX IF NOT EXISTS "holdings_account_token_external_uq"
  ON "holdings" ("account_id", "token_id", "external_id")
  WHERE "external_id" IS NOT NULL;
