// GENERATED by scripts/generate-design-tokens.ts from
// packages/frontend/ui/src/design-tokens/tokens.ts — DO NOT EDIT.
import SwiftUI

struct ScaniColors {
    let background: Color
    let foreground: Color
    let card: Color
    let cardForeground: Color
    let popover: Color
    let popoverForeground: Color
    let primary: Color
    let primaryForeground: Color
    let secondary: Color
    let secondaryForeground: Color
    let muted: Color
    let mutedForeground: Color
    let accent: Color
    let accentForeground: Color
    let destructive: Color
    let destructiveForeground: Color
    let border: Color
    let input: Color
    let ring: Color
    let chart1: Color
    let chart2: Color
    let chart3: Color
    let chart4: Color
    let chart5: Color

    static let light = ScaniColors(
        background: Color(red: 1.0000, green: 1.0000, blue: 1.0000),
        foreground: Color(red: 0.0392, green: 0.0392, blue: 0.0392),
        card: Color(red: 1.0000, green: 1.0000, blue: 1.0000),
        cardForeground: Color(red: 0.0392, green: 0.0392, blue: 0.0392),
        popover: Color(red: 1.0000, green: 1.0000, blue: 1.0000),
        popoverForeground: Color(red: 0.0392, green: 0.0392, blue: 0.0392),
        primary: Color(red: 0.0902, green: 0.0902, blue: 0.0902),
        primaryForeground: Color(red: 0.9804, green: 0.9804, blue: 0.9804),
        secondary: Color(red: 0.9608, green: 0.9608, blue: 0.9608),
        secondaryForeground: Color(red: 0.0902, green: 0.0902, blue: 0.0902),
        muted: Color(red: 0.9608, green: 0.9608, blue: 0.9608),
        mutedForeground: Color(red: 0.4510, green: 0.4510, blue: 0.4510),
        accent: Color(red: 0.9608, green: 0.9608, blue: 0.9608),
        accentForeground: Color(red: 0.0902, green: 0.0902, blue: 0.0902),
        destructive: Color(red: 0.9373, green: 0.2667, blue: 0.2667),
        destructiveForeground: Color(red: 0.9804, green: 0.9804, blue: 0.9804),
        border: Color(red: 0.8980, green: 0.8980, blue: 0.8980),
        input: Color(red: 0.8980, green: 0.8980, blue: 0.8980),
        ring: Color(red: 0.0392, green: 0.0392, blue: 0.0392),
        chart1: Color(red: 0.9059, green: 0.4314, blue: 0.3137),
        chart2: Color(red: 0.1647, green: 0.6157, blue: 0.5647),
        chart3: Color(red: 0.1529, green: 0.2784, blue: 0.3294),
        chart4: Color(red: 0.9098, green: 0.7686, blue: 0.4078),
        chart5: Color(red: 0.9569, green: 0.6431, blue: 0.3843)
    )

    static let dark = ScaniColors(
        background: Color(red: 0.0392, green: 0.0392, blue: 0.0392),
        foreground: Color(red: 0.9804, green: 0.9804, blue: 0.9804),
        card: Color(red: 0.0392, green: 0.0392, blue: 0.0392),
        cardForeground: Color(red: 0.9804, green: 0.9804, blue: 0.9804),
        popover: Color(red: 0.0392, green: 0.0392, blue: 0.0392),
        popoverForeground: Color(red: 0.9804, green: 0.9804, blue: 0.9804),
        primary: Color(red: 0.9804, green: 0.9804, blue: 0.9804),
        primaryForeground: Color(red: 0.0902, green: 0.0902, blue: 0.0902),
        secondary: Color(red: 0.1490, green: 0.1490, blue: 0.1490),
        secondaryForeground: Color(red: 0.9804, green: 0.9804, blue: 0.9804),
        muted: Color(red: 0.1490, green: 0.1490, blue: 0.1490),
        mutedForeground: Color(red: 0.6392, green: 0.6392, blue: 0.6392),
        accent: Color(red: 0.1490, green: 0.1490, blue: 0.1490),
        accentForeground: Color(red: 0.9804, green: 0.9804, blue: 0.9804),
        destructive: Color(red: 0.4980, green: 0.1137, blue: 0.1137),
        destructiveForeground: Color(red: 0.9804, green: 0.9804, blue: 0.9804),
        border: Color(red: 0.1490, green: 0.1490, blue: 0.1490),
        input: Color(red: 0.1490, green: 0.1490, blue: 0.1490),
        ring: Color(red: 0.8314, green: 0.8314, blue: 0.8314),
        chart1: Color(red: 0.1490, green: 0.3843, blue: 0.8510),
        chart2: Color(red: 0.1804, green: 0.7216, blue: 0.5412),
        chart3: Color(red: 0.9098, green: 0.5490, blue: 0.1882),
        chart4: Color(red: 0.6863, green: 0.3412, blue: 0.8588),
        chart5: Color(red: 0.8863, green: 0.2118, blue: 0.4392)
    )
}
