import { describe, expect, test } from 'bun:test';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

/**
 * SC-656. A message that tells the reader to run something has to name
 * something this repository actually has.
 *
 * SC-651 was the instance: the published docs, three runtime refusal messages
 * and the suite that pinned them all prescribed a per-worktree gate script
 * that is not shipped here. A reader who did exactly what the message said
 * got "no such file", and the tests went on passing because they pinned the
 * wording rather than the property.
 *
 * WHY THIS IS SCOPED TO PRESCRIPTIONS AND NOT TO REFERENCES. The obvious
 * wider rule — "no file names a path that does not resolve" — was measured
 * before it was rejected: 81 backticked path references resolve nowhere on
 * this tree, and the large majority are HISTORICAL and correct as prose
 * (`packages/integrations/...` naming what is now `packages/clients/...`,
 * `v2/...` naming what is now `v3/...`). A guard that fires on those is a
 * guard nobody can leave switched on, and a guard nobody leaves on is worse
 * than none because it reads as coverage. What a reader can be sent to DO is
 * the part that is actionably wrong, so that is what this checks.
 */

const REPO_ROOT = path.resolve(import.meta.dir, '../..');

/**
 * Exempt, and both for reasons that are not convenience:
 *
 * `migrations/**` is IMMUTABLE. `migration-files.ts` hashes each migration
 * with `sha256(sql)` over the whole file, comments included, and
 * `migration-runner.ts` refuses the entire run when a shipped migration's
 * hash stops matching what was recorded. Measured: rewriting one comment
 * character in `0050_sc357_...sql` moves the digest from `6ff6718ca7fadff3`
 * to `1d5579ef037011b9`, which would refuse migrations on every deployment
 * that had already applied it — ours and every self-hoster's. A prescription
 * frozen inside one is a thing to know, not a thing to repair.
 *
 * `CHANGELOG.md` is generated by release-please from commit history. Editing
 * it edits the past and the next release overwrites it anyway.
 */
const EXEMPT = (file: string): boolean =>
  file.startsWith('packages/infra/db/src/migrations/') || file === 'CHANGELOG.md';

/** Every `scripts` name declared by any workspace manifest in the tree. */
function declaredScriptNames(files: readonly string[]): ReadonlySet<string> {
  const names = new Set<string>();
  for (const f of files) {
    if (path.basename(f) !== 'package.json') continue;
    try {
      const scripts = JSON.parse(readFileSync(path.join(REPO_ROOT, f), 'utf8')).scripts ?? {};
      for (const n of Object.keys(scripts)) names.add(n);
    } catch {
      // A manifest this test cannot parse is not this test's finding.
    }
  }
  return names;
}

/**
 * A path is resolved against the repo root AND as a suffix of any tracked
 * path. The suffix arm is load-bearing rather than lax: `scripts/run.ts`
 * written in `apps/e2e` prose means `apps/e2e/scripts/run.ts`, and a check
 * that reads it as a root path reports three correct references as broken.
 */
function makeResolver(files: readonly string[]) {
  const exact = new Set(files);
  return (p: string): boolean => exact.has(p) || files.some((f) => f.endsWith(`/${p}`));
}

export function unresolvableCommands(
  text: string,
  resolvesPath: (p: string) => boolean,
  scriptNames: ReadonlySet<string>
): ReadonlyArray<string> {
  const found: string[] = [];
  for (const m of text.matchAll(/\bbun\s+(scripts\/[A-Za-z0-9_./-]+\.ts)/g)) {
    if (!resolvesPath(m[1] as string)) found.push(`bun ${m[1]}`);
  }
  for (const m of text.matchAll(/\bbun run ([a-z][a-z0-9]*(?::[a-z0-9-]+)+)/g)) {
    if (!scriptNames.has(m[1] as string)) found.push(`bun run ${m[1]}`);
  }
  return found;
}

function trackedFiles(): readonly string[] {
  const run = Bun.spawnSync(['git', 'ls-files'], { cwd: REPO_ROOT });
  return run.stdout
    .toString()
    .split('\n')
    .filter(Boolean)
    .filter((f) => existsSync(path.join(REPO_ROOT, f)));
}

describe('a prescribed command resolves in this repo', () => {
  const files = trackedFiles();
  const resolvesPath = makeResolver(files);
  const scriptNames = declaredScriptNames(files);

  /**
   * The self-test. Without it this file passes on a tree it never read, on a
   * regex that stopped matching, or on a resolver that says yes to
   * everything — and a green run would look identical to a clean repo. That
   * is the failure the whole ticket is about, so it is checked here rather
   * than assumed.
   */
  test('the check can still tell a broken prescription from a working one', () => {
    // Assembled rather than written out. A literal probe would be a live
    // broken prescription inside a tracked file, so this check would flag its
    // own source — which is exactly what it did until CI caught it: the local
    // run passed only because the file was still untracked and `git ls-files`
    // could not see it.
    const absentPath = `${'scripts'}/definitely-absent-sc656.ts`;
    const absentName = `${'definitely'}:absent`;
    const probe = `run \`bun ${absentPath}\` and \`bun run ${absentName}\``;
    expect(unresolvableCommands(probe, resolvesPath, scriptNames)).toEqual([
      `bun ${absentPath}`,
      `bun run ${absentName}`,
    ]);

    // These two resolve, so they are safe to spell out — and spelling them
    // out is the point: the anti-probe has to be the real shape.
    const antiProbe = 'run `bun scripts/migrate.ts`, or `bun run db:migrate`';
    expect(unresolvableCommands(antiProbe, resolvesPath, scriptNames)).toEqual([]);
  });

  test('the resolver reads the real tree, not an empty list', () => {
    // A resolver over zero files says "unresolvable" to everything and the
    // anti-probe above would still pass, because it asserts on emptiness.
    expect(files.length).toBeGreaterThan(1000);
    expect(scriptNames.has('db:migrate')).toBe(true);
    expect(resolvesPath('scripts/migrate.ts')).toBe(true);
    expect(resolvesPath('scripts/definitely-absent-sc656.ts')).toBe(false);
  });

  test('no tracked file prescribes a command this repo cannot run', () => {
    const offences: string[] = [];
    for (const f of files) {
      if (EXEMPT(f)) continue;
      let body: string;
      try {
        body = readFileSync(path.join(REPO_ROOT, f), 'utf8');
      } catch {
        continue;
      }
      for (const cmd of unresolvableCommands(body, resolvesPath, scriptNames)) {
        offences.push(`${f}: ${cmd}`);
      }
    }
    expect(offences).toEqual([]);
  });
});
