#!/usr/bin/env bun
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { hslTripleToRgb } from '../packages/frontend/ui/src/design-tokens/hsl';
import { COLOR_TOKENS } from '../packages/frontend/ui/src/design-tokens/tokens';

const ROOT = path.join(import.meta.dir, '..');
const KT_PATH = path.join(
  ROOT,
  'apps/mobile/android/src/main/kotlin/xyz/scani/mobile/android/ui/theme/ScaniColors.kt'
);
const SWIFT_PATH = path.join(ROOT, 'apps/mobile/ios/iosApp/ScaniColors.swift');

const GEN_HEADER =
  '// GENERATED by scripts/generate-design-tokens.ts from\n' +
  '// packages/frontend/ui/src/design-tokens/tokens.ts — DO NOT EDIT.';

function camel(name: string): string {
  return name.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

function hex(triple: string): string {
  const { r, g, b } = hslTripleToRgb(triple);
  const h = (n: number) => n.toString(16).padStart(2, '0').toUpperCase();
  return `0xFF${h(r)}${h(g)}${h(b)}`;
}

function srgb(triple: string): string {
  const { r, g, b } = hslTripleToRgb(triple);
  const c = (n: number) => (n / 255).toFixed(4);
  return `red: ${c(r)}, green: ${c(g)}, blue: ${c(b)}`;
}

function renderKotlin(): string {
  const fields = Object.keys(COLOR_TOKENS)
    .map((name) => `    val ${camel(name)}: Color,`)
    .join('\n');
  const instance = (mode: 'light' | 'dark') =>
    Object.entries(COLOR_TOKENS)
      .map(([name, v]) => `    ${camel(name)} = Color(${hex(v[mode])}),`)
      .join('\n');
  return `${GEN_HEADER}
package xyz.scani.mobile.android.ui.theme

import androidx.compose.ui.graphics.Color

data class ScaniColors(
${fields}
)

val LightScaniColors = ScaniColors(
${instance('light')}
)

val DarkScaniColors = ScaniColors(
${instance('dark')}
)
`;
}

function renderSwift(): string {
  const fields = Object.keys(COLOR_TOKENS)
    .map((name) => `    let ${camel(name)}: Color`)
    .join('\n');
  // Swift call args take no trailing comma — join with ',\n', no tail comma.
  const instance = (mode: 'light' | 'dark') =>
    Object.entries(COLOR_TOKENS)
      .map(([name, v]) => `        ${camel(name)}: Color(${srgb(v[mode])})`)
      .join(',\n');
  return `${GEN_HEADER}
import SwiftUI

struct ScaniColors {
${fields}

    static let light = ScaniColors(
${instance('light')}
    )

    static let dark = ScaniColors(
${instance('dark')}
    )
}
`;
}

function safeRead(p: string): string {
  try {
    return readFileSync(p, 'utf8');
  } catch {
    return '';
  }
}

function main(): void {
  const kt = renderKotlin();
  const swift = renderSwift();
  const isCheck = process.argv.includes('--check');

  if (isCheck) {
    if (safeRead(KT_PATH) !== kt || safeRead(SWIFT_PATH) !== swift) {
      console.error('❌ Generated design-token themes are out of date. Run: bun run tokens:gen');
      process.exit(1);
    }
    console.log('✓ Design-token themes in sync');
    return;
  }

  writeFileSync(KT_PATH, kt);
  writeFileSync(SWIFT_PATH, swift);
  console.log(`✓ Wrote ${path.relative(ROOT, KT_PATH)} and ${path.relative(ROOT, SWIFT_PATH)}`);
}

main();
