#!/usr/bin/env bun

//
// Regenerates the per-package `paths-filter` block in
// `.github/workflows/ci.yml` from the workspace list in root
// `package.json`. Adding a new package under `packages/*/*/` no longer
// requires hand-editing CI — run `bun run ci:gen`.
//
// Pass `--check` to fail (exit 1) when the generated content drifts from
// what's currently in ci.yml. The repo's `bun run check` invokes this so
// CI catches drift before merge.
//
// Scope: only `packages/*/*/` workspaces. Apps stay manually listed in
// ci.yml — adding a new app is rare and usually couples to other CI/deploy
// changes anyway, so a script-managed app list would hide more than it
// helps.
//
// The filter list itself is reference metadata — the test job runs the
// full repo suite (`bun run test`) regardless. Per-package filters are
// kept around so future per-package CI optimizations have a starting
// point without re-deriving the workspace catalogue.

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { Glob } from 'bun';

const REPO_ROOT = path.resolve(import.meta.dir, '..');
const CI_PATH = path.join(REPO_ROOT, '.github/workflows/ci.yml');

interface Workspace {
  label: string;
  path: string;
}

function discoverPackageWorkspaces(): Workspace[] {
  const out: Workspace[] = [];
  const seen = new Set<string>();

  const glob = new Glob('packages/*/*/package.json');
  for (const match of glob.scanSync({ cwd: REPO_ROOT, onlyFiles: true })) {
    const dir = path.dirname(match);
    const label = path.basename(dir);
    if (seen.has(label)) {
      throw new Error(
        `Duplicate workspace label '${label}' (collision between two packages with the same leaf-dir name). Disambiguate before regenerating.`
      );
    }
    seen.add(label);
    out.push({ label, path: dir });
  }

  return out.sort((a, b) => a.label.localeCompare(b.label));
}

function generateFiltersBlock(workspaces: Workspace[]): string {
  return workspaces
    .map((w) => `            ${w.label}:\n              - '${w.path}/**'`)
    .join('\n');
}

function applyMarkers(
  content: string,
  beginPattern: string,
  endPattern: string,
  replacement: string
): string {
  // Capture the BEGIN line (with trailing newline) and the END line
  // (with its leading newline + indent), replacing everything in between
  // with the new body. The body itself has no trailing newline; the
  // captured `$2` carries the newline before the END marker.
  const re = new RegExp(`(${beginPattern}\\n)[\\s\\S]*?(\\n[\\t ]*${endPattern})`);
  if (!re.test(content)) {
    throw new Error(`Markers not found: ${beginPattern} … ${endPattern}`);
  }
  return content.replace(re, `$1${replacement}$2`);
}

function main(): void {
  const workspaces = discoverPackageWorkspaces();
  if (workspaces.length === 0) {
    throw new Error('No package workspaces found under packages/*/*/');
  }

  const filtersBlock = generateFiltersBlock(workspaces);

  const original = readFileSync(CI_PATH, 'utf8');
  let next = original;

  next = applyMarkers(
    next,
    '# BEGIN auto:filters \\(generated by scripts/generate-ci-filters\\.ts — do not edit\\)',
    '# END auto:filters',
    filtersBlock
  );

  const isCheck = process.argv.includes('--check');

  if (isCheck) {
    if (original !== next) {
      console.error('❌ CI filters out of sync with packages/*/*/ workspaces.');
      console.error('   Run: bun run ci:gen');
      process.exit(1);
    }
    console.log(`✓ CI filters in sync (${workspaces.length} packages)`);
    return;
  }

  if (original === next) {
    console.log(`✓ CI filters already up to date (${workspaces.length} packages)`);
    return;
  }

  writeFileSync(CI_PATH, next);
  console.log(
    `✓ Wrote ${workspaces.length} package filters to ${path.relative(REPO_ROOT, CI_PATH)}`
  );
}

main();
