#!/usr/bin/env bun
/**
 * Sync per-app .env files from the root .env (single source of truth).
 *
 * The contract: each app's `.env.example` enumerates the variables that
 * app reads. This script parses every key it finds in the example
 * (including commented-out optional keys like `# OPENAI_API_KEY=`),
 * looks each one up in the root `.env`, and writes the resolved subset
 * to the app's runtime `.env` file.
 *
 * Adding a new variable to an app is therefore a one-file change: drop
 * it into that app's `.env.example`. The sync script auto-picks it up.
 *
 * Run automatically by the `env-sync` compose service on `docker compose up`,
 * and by `bun run dev:stack` before the stack boots. Safe to re-run;
 * overwrites target files every time.
 *
 *   bun scripts/sync-env.ts          # uses default root .env
 *   ROOT_ENV=/path/to/.env bun scripts/sync-env.ts
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const thisFile = new URL(import.meta.url).pathname;
const repoRoot = resolve(dirname(thisFile), '..');
const rootEnvPath = process.env.ROOT_ENV ?? resolve(repoRoot, '.env');

if (!existsSync(rootEnvPath)) {
  console.error(
    `❌ root .env not found at ${rootEnvPath}.\n` +
      `   Run \`cp .env.example .env\` first, then re-run this script.`
  );
  process.exit(1);
}

// Minimal KEY=VALUE parser. Does not handle multiline values or shell
// expansion — neither is used in our .env.example. Quoted strings get
// their outer quotes stripped for compatibility with shells that re-read
// the file directly (e.g. `source .env`).
function parseEnv(src: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const rawLine of src.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

// Extract every variable name an app declares in its `.env.example`.
// Matches both active entries (`FOO=bar`) and commented-out optional
// entries (`# FOO=`) — the latter document "this var is used but not
// required". A var makes it into the output only if the root .env
// actually sets it.
const ENV_KEY_RE = /^\s*#?\s*([A-Z][A-Z0-9_]*)\s*=/;

function parseAllowedKeys(src: string): string[] {
  const keys = new Set<string>();
  for (const rawLine of src.split('\n')) {
    const match = rawLine.match(ENV_KEY_RE);
    if (match) keys.add(match[1]);
  }
  return [...keys];
}

const root = parseEnv(readFileSync(rootEnvPath, 'utf8'));

const HEADER = `# Auto-generated by scripts/sync-env.ts from the root .env.
# Do NOT edit by hand — your changes will be overwritten on the next sync.
# To add or remove a variable for this app, edit this directory's
# .env.example, then re-run \`bun scripts/sync-env.ts\`.
`;

function render(keys: string[]): string {
  const lines: string[] = [HEADER];
  for (const key of keys) {
    const value = root[key];
    if (value === undefined) continue;
    lines.push(`${key}=${value}`);
  }
  lines.push('');
  return lines.join('\n');
}

// Per-app output filename override. Next.js (apps/admin) reads `.env.local`
// with higher priority than `.env` and our existing docs tell operators to
// put values there — stick with that. Everyone else gets plain `.env`.
const OUTPUT_FILENAME: Record<string, string> = {
  admin: '.env.local',
};

const appsDir = resolve(repoRoot, 'apps');
const apps = readdirSync(appsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .filter((name) => existsSync(resolve(appsDir, name, '.env.example')));

if (apps.length === 0) {
  console.warn('⚠️  No apps with .env.example found under apps/ — nothing to do.');
  process.exit(0);
}

for (const app of apps) {
  const examplePath = resolve(appsDir, app, '.env.example');
  const allowedKeys = parseAllowedKeys(readFileSync(examplePath, 'utf8'));
  const outputName = OUTPUT_FILENAME[app] ?? '.env';
  const outPath = resolve(appsDir, app, outputName);
  mkdirSync(dirname(outPath), { recursive: true });
  const rendered = render(allowedKeys);
  // Skip the write when content is unchanged. Vite's dotenv watcher
  // restarts the dev server on any mtime bump, and an unconditional
  // rewrite here (fired every time the `env-sync` compose service reruns,
  // e.g. on backend rebuilds) has repeatedly deadlocked Vite mid-restart.
  // Idempotency fixes that at the source.
  const current = existsSync(outPath) ? readFileSync(outPath, 'utf8') : null;
  if (current === rendered) {
    const resolved = allowedKeys.filter((k) => root[k] !== undefined).length;
    console.log(
      `↻ apps/${app}/${outputName} unchanged — ${resolved}/${allowedKeys.length} vars resolved (skipped)`
    );
    continue;
  }
  writeFileSync(outPath, rendered, { mode: 0o600 });
  const resolved = allowedKeys.filter((k) => root[k] !== undefined).length;
  console.log(
    `✅ wrote apps/${app}/${outputName} — ${resolved}/${allowedKeys.length} vars resolved from root .env`
  );
}
